sudo: required
dist: trusty
language: cpp
cache: apt

branches:
  only:
    - 'master'
    - 'dev'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -qq install -y qt5-default qtbase5-dev libbotan1.10-dev gcc-4.8 libqrencode-dev libzbar-dev libappindicator-dev libqtshadowsocks-dev cmake3

script:
  - mkdir build && cd build
  - cmake ..
  - make

